import Head from "next/head";
import Nav from "@/components/Nav";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import PropertyOverview from "@/components/PropertyOverview";
import CustomersOverview from "@/components/CustomersOverview";
import ListingsOverview from "@/components/ListingsOverview";
import SalesOverview from "@/components/SalesOverview";
import { Text, Box } from "@chakra-ui/react";
import { Image } from "@chakra-ui/react";
import Balance from "@/components/Balance";
import TopSelling from "@/components/TopSelling";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`} bg="#fbfcfc">
        <Nav />
        <Box display="flex">
          <Image
            objectFit="cover"
            src="/Rectangle 12749.png"
            alt="Greeting Icon"
          />
          <Text color="#191919" fontSize={20} fontWeight={600}>
            Hi Ahmed
          </Text>
        </Box>
        <p fontSize={12} color="#3D3D3D">
          Welcome to your new dashboard
        </p>
        <Box display="flex" gap={5}>
          <SalesOverview />
          <Box display="flex" flexDirection="column" gap={5}>
            <PropertyOverview />
            <CustomersOverview />
          </Box>
        </Box>
        <Box display="flex" gap={5} mt={30}>
          <ListingsOverview />
          <Balance />
          <TopSelling />
        </Box>
      </main>
    </>
  );
}
